#!/usr/bin/env python3
"""
Extract Chrome cookies and save them in Netscape format for yt-dlp.

Usage:
    python extract_chrome_cookies.py [output_file]

If output_file is not provided, saves to 'youtube_cookies.txt' in the backend directory.
"""

import os
import sys
import sqlite3
import json
from pathlib import Path
from datetime import datetime, timezone

def get_chrome_cookies_path():
    """Get the path to Chrome's cookies database on Windows."""
    appdata = os.getenv('APPDATA')
    local_appdata = os.getenv('LOCALAPPDATA')
    
    # Try different Chrome cookie locations
    possible_paths = [
        os.path.join(local_appdata, r'Google\Chrome\User Data\Default\Cookies'),
        os.path.join(local_appdata, r'Google\Chrome\User Data\Profile 1\Cookies'),
        os.path.join(appdata, r'Google\Chrome\User Data\Default\Cookies'),
    ]
    
    for path in possible_paths:
        if path and os.path.exists(path):
            return path
    
    return None

def chrome_time_to_unix(chrome_time):
    """Convert Chrome timestamp to Unix timestamp."""
    # Chrome timestamp is microseconds since 1601-01-01
    # Unix timestamp is seconds since 1970-01-01
    # Difference: 11644473600 seconds
    return chrome_time / 1000000 - 11644473600

def extract_chrome_cookies(cookies_db_path=None, domain_filter='youtube.com'):
    """Extract cookies from Chrome's SQLite database."""
    cookies = []
    
    # Try browser_cookie3 first (more reliable)
    try:
        import browser_cookie3
        print("Using browser_cookie3 to extract cookies...")
        cookies_list = browser_cookie3.chrome(domain_name=domain_filter)
        cookies = []
        for cookie in cookies_list:
            expires = cookie.expires if hasattr(cookie, 'expires') and cookie.expires else 0
            cookies.append({
                'name': cookie.name,
                'value': cookie.value,
                'domain': cookie.domain,
                'path': cookie.path if hasattr(cookie, 'path') else '/',
                'expires': expires,
                'secure': cookie.secure if hasattr(cookie, 'secure') else False,
                'httponly': getattr(cookie, 'HttpOnly', False)
            })
        return cookies
    except ImportError:
        print("browser_cookie3 not installed. Trying direct SQLite method...")
    except Exception as e:
        print(f"browser_cookie3 method failed: {e}")
        print("Trying direct SQLite method...")
    
    # Fallback to direct SQLite method
    if not cookies_db_path:
        cookies_db_path = get_chrome_cookies_path()
    
    if not cookies_db_path:
        raise Exception("Could not find Chrome cookies database and browser_cookie3 is not available")
    
    try:
        # Copy the database to a temp location because Chrome locks it
        import tempfile
        import shutil
        
        temp_db = tempfile.NamedTemporaryFile(delete=False, suffix='.db')
        temp_db.close()
        
        try:
            shutil.copy2(cookies_db_path, temp_db.name)
            
            conn = sqlite3.connect(temp_db.name)
            cursor = conn.cursor()
            
            # Query cookies for the specified domain
            query = """
                SELECT name, value, host_key, path, expires_utc, is_secure, is_httponly
                FROM cookies
                WHERE host_key LIKE ?
                ORDER BY host_key, name
            """
            
            cursor.execute(query, (f'%{domain_filter}%',))
            
            for row in cursor.fetchall():
                name, value, host_key, path, expires_utc, is_secure, is_httponly = row
                
                # Convert Chrome timestamp to Unix timestamp
                expires = chrome_time_to_unix(expires_utc) if expires_utc else 0
                
                cookies.append({
                    'name': name,
                    'value': value,
                    'domain': host_key,
                    'path': path or '/',
                    'expires': expires,
                    'secure': bool(is_secure),
                    'httponly': bool(is_httponly)
                })
            
            conn.close()
        finally:
            os.unlink(temp_db.name)
            
    except Exception as e:
        raise Exception(f"Failed to extract cookies: {e}")
    
    return cookies

def save_netscape_format(cookies, output_path):
    """Save cookies in Netscape format."""
    with open(output_path, 'w', encoding='utf-8') as f:
        # Write Netscape format header
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by extract_chrome_cookies.py\n")
        f.write(f"# Generated: {datetime.now().isoformat()}\n\n")
        
        # Write cookies
        for cookie in cookies:
            domain = cookie['domain']
            # Netscape format: domain, flag, path, secure, expiration, name, value
            # flag: TRUE if all subdomains, FALSE otherwise
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie['path']
            secure = 'TRUE' if cookie['secure'] else 'FALSE'
            expires = str(int(cookie['expires'])) if cookie['expires'] > 0 else '0'
            name = cookie['name']
            value = cookie['value']
            
            # Format: domain flag path secure expiration name value
            line = f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
            f.write(line)
    
    print(f"Saved {len(cookies)} cookies to {output_path}")

def main():
    output_file = sys.argv[1] if len(sys.argv) > 1 else None
    
    if not output_file:
        backend_dir = Path(__file__).parent
        output_file = backend_dir / 'youtube_cookies.txt'
    else:
        output_file = Path(output_file)
    
    print("Extracting Chrome cookies for YouTube...")
    
    try:
        cookies = extract_chrome_cookies(domain_filter='youtube.com')
        
        if not cookies:
            print("WARNING: No YouTube cookies found.")
            print("Make sure you're logged into YouTube in Chrome.")
            sys.exit(1)
        
        save_netscape_format(cookies, output_file)
        print(f"\nSuccess! Cookies saved to: {output_file}")
        print(f"\nTo use these cookies, add to your backend/.env file:")
        print(f"YOUTUBE_COOKIES={output_file.absolute()}")
        
    except PermissionError as e:
        print(f"ERROR: {e}")
        print("\nThis script needs administrator privileges to access Chrome's cookies.")
        print("\nOPTION 1: Run as Administrator")
        print("  1. Close this window")
        print("  2. Right-click PowerShell/Command Prompt")
        print("  3. Select 'Run as administrator'")
        print("  4. Navigate to the backend directory and run:")
        print(f"     python {Path(__file__).name}")
        print("\nOPTION 2: Manual Cookie Export (No Admin Required)")
        print("  1. Install 'Get cookies.txt LOCALLY' Chrome extension:")
        print("     https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc")
        print("  2. Go to youtube.com and make sure you're logged in")
        print("  3. Click the extension icon")
        print("  4. Click 'Export' and save as 'youtube_cookies.txt'")
        print(f"  5. Move the file to: {output_file.absolute()}")
        print("  6. Add to backend/.env:")
        print(f"     YOUTUBE_COOKIES={output_file.absolute()}")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        print("\nYou may need to install browser-cookie3:")
        print("  pip install browser-cookie3")
        print("\nOr use the manual cookie export method (see OPTION 2 above).")
        sys.exit(1)

if __name__ == '__main__':
    main()

